name: Tempus Letter Broker deployment

on:
  push:
    branches: ["**"]
    paths-ignore:
      - '**/*.md'
      - '**/LICENSE'
      - '**/.gitignore'

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: ESLint
        run: npm run lint

  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: node:test
        run: node --test

  validate:
    name: Validate openapi contract
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: validate
        run: npm run openapi:validate

  build-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    needs:
      - lint
      - tests
      - validate
    runs-on: ubuntu-latest
    environment:
      name: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.3'
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHubWorkflow
          aws-region: eu-west-2

      # assume the relevant role via AWS Profile
      - run: sh ./.github/scripts/assume-role-profile.sh
        env:
          ROLE_ARN: ${{ secrets.ASSUMED_ROLE }}

      # setup docker
      - uses: docker/setup-buildx-action@v3
      - uses: docker/setup-qemu-action@v3

      # sam validate
      - run: sam validate --lint

      # sam build
      - run: sam build --use-container

      # deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name tempus-letter-broker --resolve-s3 --resolve-image-repos --capabilities CAPABILITY_IAM --region eu-west-2 --profile assumed-role --parameter-overrides Environment=dev OnPremIpRange=192.168.0.1/16